project_id = "fgvemvzuczyrptmduyjq"

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-external-auth]
verify_jwt = false